In [1]:
import numpy as np
import torch

In [2]:
A = np.array([0,2,4])

In [3]:
B1 = torch.Tensor(A)

In [17]:
B2 = torch.as_tensor(A)

In [18]:
B3 = torch.from_numpy(A)

In [7]:
B1

tensor([0., 2., 4.])

In [8]:
B2

tensor([0, 2, 4])

In [9]:
B3

tensor([0, 2, 4])

In [10]:
A[0]=1

In [11]:
B1

tensor([0., 2., 4.])

In [12]:
B2

tensor([1, 2, 4])

In [13]:
B3

tensor([1, 2, 4])